name: miniguru
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # Database & Storage
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Network & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Media
  image_picker: ^0.8.9
  file_picker: ^8.1.2
  video_player: ^2.9.2
  youtube_player_iframe: ^5.1.2
  
  # Payments
  razorpay_flutter: ^1.3.7
  
  # Utilities
  intl: ^0.19.0
  permission_handler: ^11.3.1
  sticky_headers: ^0.3.0+2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mg-logo.png
    - assets/bag.png
    - assets/ic_logo.png
    - assets/shopping-cart.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mg-logo.png"
  min_sdk_android: 21